### ISSUE TITLE
?? THE BEST IS ??

### ISSUE THREAD

**Issue by kel12345678** [Hax4us/TermuxAlpine#10]
hello  the best android emulator is termux simply? termuxalpine? termuxkalinethunter?termuxarch? or a new terminal?  for pentest in android smartphone.
my phone is rooted aarch64 oreo8 sony xperia g3221 xa1  .thanks for your help(sorry for my bad english)

**Comment by bensh4** [comment]
You can give a try on *Arch*

**Comment by bensh4** [comment]
@kel12345678 You can give a try on *Arch*  https://github.com/sdrausty/termux-archlinux
