### ISSUE TITLE
Is it possible to write file into outside storage? eg. Downloads/ directory

### ISSUE THREAD

**Issue by dlintw** [Hax4us/TermuxAlpine#11]
I wan to write a script to keep log in outside directory which android system can access.  Is it possible?

**Comment by Hax4us** [comment]
Yes You can access ( if android system can access)

**Comment by dlintw** [comment]
I have ~/storage in termux. In Alpine, it can access /storage, the content is emulated and can not access .

**Comment by Hax4us** [comment]
You directly use `/sdcard`
