### ISSUE TITLE
On Oreo /etc/resolv.conf is empty

### ISSUE THREAD

**Issue by taichifan** [Hax4us/TermuxAlpine#13]
On Oreo /etc/resolv.conf is empty because getprop gives a different value than Nougat, etc. I've tested it on 8.1 on LG Stylo 4 and Nexus 6p on 8.0. Need to check the size of the file and use default values if it's empty.

**Comment by gdw2** [comment]
Same on Pie 9.0

**Comment by taichifan** [comment]
I've submitted a pull request that sets the file to defaults if it's empty.

**Comment by andresitodeguzman** [comment]
Got it fixed by extracting the "alpine-minirootfs-3.9.3-aarch64.tar.gz"

**Comment by Hax4us** [comment]
Closing it with Closing it with https://github.com/Hax4us/TermuxAlpine/commit/ca8b85a25a66e089a0f08d870cb253f3065e2da8
