### ISSUE TITLE
Cannot setup gui.

### ISSUE THREAD

**Issue by amsitlab** [Hax4us/TermuxAlpine#17]
I was following intructions on your [blog](https://www.hax4us.com/2018/12/setup-basic-gui-in-termuxalpine.html?m=1) , but thats is not working, displaying some error/warning seem like *"Cannot read display :1"*

**Comment by Hax4us** [comment]
Provide Screenshots

**Comment by Vlone12536** [comment]
I launched Xvfb:
![image](https://user-images.githubusercontent.com/46228973/61585313-fceb4d00-ab60-11e9-9ac8-64fdf8853a78.png)

and after i try to run x11vnc, i got an error: 
` shmget(scanline) failed.
shmget: Invalid argument `


![image](https://user-images.githubusercontent.com/46228973/61585322-112f4a00-ab61-11e9-842d-1990e6599937.png)

how can i fix it?

**Comment by Vlone12536** [comment]
i just need to add `-noshm` to `x11vnc`

now all works fine
