### ISSUE TITLE
Proot Crashed when I installing openjdk

### ISSUE THREAD

**Issue by ghost** [Hax4us/TermuxAlpine#31]
When I install openjdk8, the proot crashed
```
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
Executing java-common-0.2-r0.trigger
proot warning: signal 11 received from process 24
```

**Comment by Hax4us** [comment]
Reinstall alpine , issue is resolved now
![Screenshot_2020-04-20-11-19-45-649_com termux](https://user-images.githubusercontent.com/30441647/79718114-e5601100-82f8-11ea-8650-ff7b18e2e480.jpg)
