### ISSUE TITLE
TermuxAlpine ,Its Posible to GUI

### ISSUE THREAD

**Issue by kangris-sket** [Hax4us/TermuxAlpine#5]
Yesterday,
I ve try install xfce4 xorg xrdp...
I want make termuxalpine gui run.
Xfce4 n xrdp succes install but xorg is missing....

Its posible run termuxalpine gui,sir..

Thanks,maybe you can help me {+_+}

**Comment by NitroNils** [comment]
@kangris-sket, did you try?

**Comment by Hax4us** [comment]
I did not tried xfce or any GUI environment but yes I tried openbox and xfce4-terminal for GUI testing and it works with x11-vnc

**Comment by kangris-sket** [comment]
@dimaguy @NitroNills

[termux@alpine home]# setup-xorg-base
/bin/sh: setup-xorg-base: not found
[termux@alpine home]#

@Hax4us thank for referance
