### ISSUE TITLE
please could you help Me compile The speech-dispatcher speech server

### ISSUE THREAD

**Issue by JanuszChmiel** [Hax4us/TermuxAlpine#54]
Dear advanced author of this script to install Alpine.
I Am visually impaired with no sight at all. And I have The possibility to use Xwayland protocol. I can use Mate desktop environment and Orca screen reader, which is packaged in Alpine Linux repository.
Unfortunately for Me, Orca screen reader packager have forgotten to add very important Orca screen dependency.
Speech-dispatcher.
This speech server is The crucial part of Orca. It can not speak without this C complex app.

Please could you help Me to build This speech server on Alpine Linux AArch64 architecture?
I have used your Bash script to install Alpine.

There are complex issues while building Speech-dispatcher.
Here is Speech-dispatcher github repository address.
https://github.com/brailcom/speechd
Sure I have followed The documentation.
But I Am getting errors.

I Am sad, because Alpine uses Mate without depend on Systemd so no errors are displaied, Alpine eve support start Linux services in Chroot mode even if Linux kernel is not presented, so it would be more than ideal distribution for visually impaired Orca users.

May be, that you will help Me.

**Comment by Hax4us** [comment]
hello sorry for late response
These are the steps

1. Update repo `apk update`
2. Clone `git clone https://github.com/brailcom/speechd`
3. Install deps `apk add bash make gcc g++ autoconf gettext-dev automake pkgconfig libtool binutils musl-dev glib-dev libdotconf-dev libsndfile-dev texinfo`
4. Prepare configure and make file `cd speechd && ./build.sh`
5. Build `./configure && make`
6. Install `make install`
