### ISSUE TITLE
no startalpine after install

### ISSUE THREAD

**Issue by dlintw** [Hax4us/TermuxAlpine#6]
I just follow the README.md, there is not startalpine to run

**Comment by bensh4** [comment]
@dlintw Did you run *bash TermuxAlpine.sh* ?

**Comment by dlintw** [comment]
ou are going to install Alpine in termux ;) Cool
 Only 1mb Yes to continue

 [*] Checking host architecture ...
 [*] Updating apt cache...
 [*] Checking for all required tools...
 • proot is OK
 • bsdtar is OK
 • curl is OK
 [*] Getting tar file...

##################################################### 100.0%

 [*] Getting SHA ...

##################################################### 100.0%

 [*] Checking integrity of file...
 [*] The script will immediately terminate in case of integrity failure
 alpine-minirootfs-3.8.1-aarch64.tar.gz: OK
 [*] Extracting...
------------------------------------------#

 [*] Email   :    lkpandey950@gmail.com
 [*] Website :    https://hax4us.com
 [*] YouTube :    https://youtube.com/hax4us

 #------------------------------------------#

 NOTE :  use --uninstall option for uninstall

 #------------------------------------------#
$ ls
TermuxAlpine
TermuxAlpine.sh
finaltouchup.sh
storage
